// <auto-generated />
using System;
using CaseItau.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseItau.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CaseItauDbContext))]
    [Migration("20260420182304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CaseItau.Domain.Entities.Fundo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT")
                        .HasColumnName("CNPJ");

                    b.Property<int>("CodigoTipo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CODIGO_TIPO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<decimal?>("Patrimonio")
                        .HasColumnType("TEXT")
                        .HasColumnName("PATRIMONIO");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoTipo");

                    b.ToTable("FUNDO", (string)null);
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.TipoFundo", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.HasKey("Codigo");

                    b.ToTable("TIPO_FUNDO", (string)null);

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Nome = "Fundo de Renda Fixa"
                        },
                        new
                        {
                            Codigo = 2,
                            Nome = "Fundo de Ações"
                        },
                        new
                        {
                            Codigo = 3,
                            Nome = "Fundo Multimercado"
                        },
                        new
                        {
                            Codigo = 4,
                            Nome = "Fundo de Câmbio"
                        },
                        new
                        {
                            Codigo = 5,
                            Nome = "Fundo de Previdência"
                        });
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.Fundo", b =>
                {
                    b.HasOne("CaseItau.Domain.Entities.TipoFundo", "TipoFundo")
                        .WithMany("Fundos")
                        .HasForeignKey("CodigoTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoFundo");
                });

            modelBuilder.Entity("CaseItau.Domain.Entities.TipoFundo", b =>
                {
                    b.Navigation("Fundos");
                });
#pragma warning restore 612, 618
        }
    }
}
