version: '3.9'

services:
  seq:
    image: datalust/seq:latest
    container_name: caseItau_seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
      - "5342:5341"
    volumes:
      - seq_data:/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caseItau_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/data/caseItau.db
      - Seq__Endpoint=http://seq:5341
    volumes:
      - sqlite_data:/data
    depends_on:
      - seq
    restart: unless-stopped

  front:
    build:
      context: ./case-itau-front
      dockerfile: Dockerfile
    container_name: caseItau_front
    ports:
      - "4200:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  sqlite_data:
  seq_data:
